name: flutter_bluetooth_basic_example
description: Demonstrates how to use the flutter_bluetooth_basic plugin.
publish_to: 'none'

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_basic:
    path: ../

flutter:
  uses-material-design: true
